### ISSUE TITLE
uninstalling the flutter_native_spalsh

### ISSUE THREAD

**Issue by phantomzidane** [henriquearthur/flutter_native_splash#53]
i have tried to uninstall the package it only removes it as a dependency but does not stop it from showing

**Comment by tenhobi** [comment]
Well, obviously. This is a generator alike package.

**Comment by phantomzidane** [comment]
Then how can i stop it?

**Comment by henriquearthur** [comment]
This package generates code for you in order to automatize manual work. If you generated a splash screen with it and remove from dependencies after, nothing will change because code is already generated. 

If you use Git or other VCS you can revert back to the commit before running the package. If you don't, well, you can't.

If it helps you, README contains the files this package modifies:

> This package modifies launch_background.xml, styles.xml and MainActivity files on Android and LaunchScreen.storyboard, Info.plist and AppDelegate on iOS.

```
Android
Your splash image will be resized to mdpi, hdpi, xhdpi, xxhdpi and xxxhdpi drawables.
An <item> tag containing a <bitmap> for your splash image drawable will be added in launch_background.xml
Background color will be added in colors.xml and referenced in launch_background.xml.
Code for full screen mode toggle will be added in styles.xml and MainActivity.

iOS
Your splash image will be resized to @3x and @2x images.
Color and image properties will be inserted in LaunchScreen.storyboard.
Code for hidden status bar toggle will be adde in Info.plist and AppDelegate.
```

**Comment by ktw1318** [comment]
it's first time to use your package , I want it to back , how can I fix the  launch_background.xml, styles.xml and so on, 

I mean that I don't need to use splash screen , how ever I can not rollback before instailing it .

just go back to the past.. please more detail guide, Please..
