### ISSUE TITLE
Splash Screen too fast at Release Mode

### ISSUE THREAD

**Issue by bagikode** [henriquearthur/flutter_native_splash#57]
Hello, I tried your package but when i run it, Splash Screen show too fast then a blank screen appears like glitch blank with interval 1 second before the first page is run. Thanks for your package :)

**Comment by alexkharech** [comment]
+1

**Comment by edufolly** [comment]
Probably this is the solution: [#54](https://github.com/henriquearthur/flutter_native_splash/issues/54#issuecomment-589237135)

**Comment by shubhambsps** [comment]
Has anyone solved the issue of fading of splash screen fastly in release mode?

**Comment by jonbhanson** [comment]
This package is designed to display a splash screen while the Flutter architecture is loading.  If the splash screen shows too fast, that means that your device is loading the Flutter architecture quickly, which is a good thing.  If you have a subsequent blank screen, that is caused by activity that is taking place within your flutter app.  You can resolve this by placing a second splash screen in your flutter app that displays while resources are loading in your flutter app.
